/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SocialRequestStandaloneSetup extends SocialRequestStandaloneSetupGenerated {

	public static void doSetup() {
		new SocialRequestStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
