/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.socialRequest;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.socialRequest.SocialRequestFactory
 * @model kind="package"
 * @generated
 */
public interface SocialRequestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "socialRequest";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/SocialRequest";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "socialRequest";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SocialRequestPackage eINSTANCE = org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.ModelImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ENTITIES = 0;

  /**
   * The feature id for the '<em><b>Repositories</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__REPOSITORIES = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.EntityImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Has User Details</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__HAS_USER_DETAILS = 1;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ATTRIBUTES = 2;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.AttributeImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 2;

  /**
   * The feature id for the '<em><b>Association</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__ASSOCIATION = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 2;

  /**
   * The feature id for the '<em><b>Modifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__MODIFIER = 3;

  /**
   * The feature id for the '<em><b>Mapped By</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__MAPPED_BY = 4;

  /**
   * The feature id for the '<em><b>Fetch Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__FETCH_TYPE = 5;

  /**
   * The feature id for the '<em><b>Validations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__VALIDATIONS = 6;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.ModifierImpl <em>Modifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.ModifierImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getModifier()
   * @generated
   */
  int MODIFIER = 3;

  /**
   * The number of structural features of the '<em>Modifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODIFIER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.IdentificationImpl <em>Identification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.IdentificationImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getIdentification()
   * @generated
   */
  int IDENTIFICATION = 4;

  /**
   * The feature id for the '<em><b>Generation Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFICATION__GENERATION_TYPE = MODIFIER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Identification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFICATION_FEATURE_COUNT = MODIFIER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.ValidationImpl <em>Validation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.ValidationImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getValidation()
   * @generated
   */
  int VALIDATION = 5;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION__MIN = 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION__MAX = 1;

  /**
   * The feature id for the '<em><b>Regex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION__REGEX = 2;

  /**
   * The number of structural features of the '<em>Validation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.RepositoryImpl <em>Repository</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.RepositoryImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getRepository()
   * @generated
   */
  int REPOSITORY = 6;

  /**
   * The feature id for the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY__ENTITY = 0;

  /**
   * The feature id for the '<em><b>Queries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY__QUERIES = 1;

  /**
   * The number of structural features of the '<em>Repository</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPOSITORY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.QueryImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__NAME = 0;

  /**
   * The feature id for the '<em><b>Is List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__IS_LIST = 1;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__PARAMS = 2;

  /**
   * The feature id for the '<em><b>Sql Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__SQL_QUERY = 3;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.ParamImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getParam()
   * @generated
   */
  int PARAM = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__TYPE = 1;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.SQLQueryImpl <em>SQL Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.SQLQueryImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getSQLQuery()
   * @generated
   */
  int SQL_QUERY = 9;

  /**
   * The feature id for the '<em><b>Select</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_QUERY__SELECT = 0;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_QUERY__FROM = 1;

  /**
   * The feature id for the '<em><b>Joins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_QUERY__JOINS = 2;

  /**
   * The feature id for the '<em><b>Where</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_QUERY__WHERE = 3;

  /**
   * The feature id for the '<em><b>Order</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_QUERY__ORDER = 4;

  /**
   * The number of structural features of the '<em>SQL Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQL_QUERY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.SelectImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 10;

  /**
   * The feature id for the '<em><b>Is Distinct</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__IS_DISTINCT = 0;

  /**
   * The feature id for the '<em><b>Clause</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__CLAUSE = 1;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.FromImpl <em>From</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.FromImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getFrom()
   * @generated
   */
  int FROM = 11;

  /**
   * The feature id for the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM__ENTITY = 0;

  /**
   * The feature id for the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM__ALIAS = 1;

  /**
   * The number of structural features of the '<em>From</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FROM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.JoinImpl <em>Join</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.JoinImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getJoin()
   * @generated
   */
  int JOIN = 12;

  /**
   * The feature id for the '<em><b>Join Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOIN__JOIN_TYPE = 0;

  /**
   * The feature id for the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOIN__ENTITY = 1;

  /**
   * The feature id for the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOIN__ALIAS = 2;

  /**
   * The feature id for the '<em><b>Join Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOIN__JOIN_CONDITION = 3;

  /**
   * The number of structural features of the '<em>Join</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JOIN_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.WhereImpl <em>Where</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.WhereImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getWhere()
   * @generated
   */
  int WHERE = 13;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE__CONDITION = 0;

  /**
   * The number of structural features of the '<em>Where</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.socialRequest.impl.OrderImpl <em>Order</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.socialRequest.impl.OrderImpl
   * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getOrder()
   * @generated
   */
  int ORDER = 14;

  /**
   * The feature id for the '<em><b>Order</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__ORDER = 0;

  /**
   * The number of structural features of the '<em>Order</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.socialRequest.Model#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Model#getEntities()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Entities();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.socialRequest.Model#getRepositories <em>Repositories</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Repositories</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Model#getRepositories()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Repositories();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Entity#isHasUserDetails <em>Has User Details</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has User Details</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Entity#isHasUserDetails()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_HasUserDetails();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.socialRequest.Entity#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Entity#getAttributes()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Attributes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Attribute#getAssociation <em>Association</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Association</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Attribute#getAssociation()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Association();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.socialRequest.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.socialRequest.Attribute#getModifier <em>Modifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Modifier</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Attribute#getModifier()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Modifier();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Attribute#getMappedBy <em>Mapped By</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mapped By</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Attribute#getMappedBy()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_MappedBy();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Attribute#getFetchType <em>Fetch Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fetch Type</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Attribute#getFetchType()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_FetchType();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.socialRequest.Attribute#getValidations <em>Validations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Validations</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Attribute#getValidations()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Validations();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Modifier <em>Modifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modifier</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Modifier
   * @generated
   */
  EClass getModifier();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Identification <em>Identification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Identification</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Identification
   * @generated
   */
  EClass getIdentification();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Identification#getGenerationType <em>Generation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Generation Type</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Identification#getGenerationType()
   * @see #getIdentification()
   * @generated
   */
  EAttribute getIdentification_GenerationType();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Validation <em>Validation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Validation</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Validation
   * @generated
   */
  EClass getValidation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Validation#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Validation#getMin()
   * @see #getValidation()
   * @generated
   */
  EAttribute getValidation_Min();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Validation#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Validation#getMax()
   * @see #getValidation()
   * @generated
   */
  EAttribute getValidation_Max();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Validation#getRegex <em>Regex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Regex</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Validation#getRegex()
   * @see #getValidation()
   * @generated
   */
  EAttribute getValidation_Regex();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Repository <em>Repository</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Repository</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Repository
   * @generated
   */
  EClass getRepository();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.socialRequest.Repository#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Repository#getEntity()
   * @see #getRepository()
   * @generated
   */
  EReference getRepository_Entity();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.socialRequest.Repository#getQueries <em>Queries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Queries</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Repository#getQueries()
   * @see #getRepository()
   * @generated
   */
  EReference getRepository_Queries();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Query#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Query#getName()
   * @see #getQuery()
   * @generated
   */
  EAttribute getQuery_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Query#isIsList <em>Is List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is List</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Query#isIsList()
   * @see #getQuery()
   * @generated
   */
  EAttribute getQuery_IsList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.socialRequest.Query#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Query#getParams()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Params();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.socialRequest.Query#getSqlQuery <em>Sql Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sql Query</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Query#getSqlQuery()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_SqlQuery();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Param#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Param#getName()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.socialRequest.Param#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Param#getType()
   * @see #getParam()
   * @generated
   */
  EReference getParam_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.SQLQuery <em>SQL Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SQL Query</em>'.
   * @see org.xtext.example.mydsl.socialRequest.SQLQuery
   * @generated
   */
  EClass getSQLQuery();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.socialRequest.SQLQuery#getSelect <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Select</em>'.
   * @see org.xtext.example.mydsl.socialRequest.SQLQuery#getSelect()
   * @see #getSQLQuery()
   * @generated
   */
  EReference getSQLQuery_Select();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.socialRequest.SQLQuery#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see org.xtext.example.mydsl.socialRequest.SQLQuery#getFrom()
   * @see #getSQLQuery()
   * @generated
   */
  EReference getSQLQuery_From();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.socialRequest.SQLQuery#getJoins <em>Joins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Joins</em>'.
   * @see org.xtext.example.mydsl.socialRequest.SQLQuery#getJoins()
   * @see #getSQLQuery()
   * @generated
   */
  EReference getSQLQuery_Joins();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.socialRequest.SQLQuery#getWhere <em>Where</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Where</em>'.
   * @see org.xtext.example.mydsl.socialRequest.SQLQuery#getWhere()
   * @see #getSQLQuery()
   * @generated
   */
  EReference getSQLQuery_Where();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.socialRequest.SQLQuery#getOrder <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Order</em>'.
   * @see org.xtext.example.mydsl.socialRequest.SQLQuery#getOrder()
   * @see #getSQLQuery()
   * @generated
   */
  EReference getSQLQuery_Order();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Select#isIsDistinct <em>Is Distinct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Distinct</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Select#isIsDistinct()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_IsDistinct();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Select#getClause <em>Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Clause</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Select#getClause()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_Clause();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.From <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>From</em>'.
   * @see org.xtext.example.mydsl.socialRequest.From
   * @generated
   */
  EClass getFrom();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.socialRequest.From#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity</em>'.
   * @see org.xtext.example.mydsl.socialRequest.From#getEntity()
   * @see #getFrom()
   * @generated
   */
  EReference getFrom_Entity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.From#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alias</em>'.
   * @see org.xtext.example.mydsl.socialRequest.From#getAlias()
   * @see #getFrom()
   * @generated
   */
  EAttribute getFrom_Alias();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Join <em>Join</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Join</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Join
   * @generated
   */
  EClass getJoin();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Join#getJoinType <em>Join Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Join Type</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Join#getJoinType()
   * @see #getJoin()
   * @generated
   */
  EAttribute getJoin_JoinType();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.socialRequest.Join#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Join#getEntity()
   * @see #getJoin()
   * @generated
   */
  EReference getJoin_Entity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Join#getAlias <em>Alias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alias</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Join#getAlias()
   * @see #getJoin()
   * @generated
   */
  EAttribute getJoin_Alias();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Join#getJoinCondition <em>Join Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Join Condition</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Join#getJoinCondition()
   * @see #getJoin()
   * @generated
   */
  EAttribute getJoin_JoinCondition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Where <em>Where</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Where</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Where
   * @generated
   */
  EClass getWhere();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Where#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Where#getCondition()
   * @see #getWhere()
   * @generated
   */
  EAttribute getWhere_Condition();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.socialRequest.Order <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Order</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Order
   * @generated
   */
  EClass getOrder();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.socialRequest.Order#getOrder <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Order</em>'.
   * @see org.xtext.example.mydsl.socialRequest.Order#getOrder()
   * @see #getOrder()
   * @generated
   */
  EAttribute getOrder_Order();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SocialRequestFactory getSocialRequestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.ModelImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ENTITIES = eINSTANCE.getModel_Entities();

    /**
     * The meta object literal for the '<em><b>Repositories</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__REPOSITORIES = eINSTANCE.getModel_Repositories();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.EntityImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '<em><b>Has User Details</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__HAS_USER_DETAILS = eINSTANCE.getEntity_HasUserDetails();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__ATTRIBUTES = eINSTANCE.getEntity_Attributes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.AttributeImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Association</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__ASSOCIATION = eINSTANCE.getAttribute_Association();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '<em><b>Modifier</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__MODIFIER = eINSTANCE.getAttribute_Modifier();

    /**
     * The meta object literal for the '<em><b>Mapped By</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__MAPPED_BY = eINSTANCE.getAttribute_MappedBy();

    /**
     * The meta object literal for the '<em><b>Fetch Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__FETCH_TYPE = eINSTANCE.getAttribute_FetchType();

    /**
     * The meta object literal for the '<em><b>Validations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__VALIDATIONS = eINSTANCE.getAttribute_Validations();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.ModifierImpl <em>Modifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.ModifierImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getModifier()
     * @generated
     */
    EClass MODIFIER = eINSTANCE.getModifier();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.IdentificationImpl <em>Identification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.IdentificationImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getIdentification()
     * @generated
     */
    EClass IDENTIFICATION = eINSTANCE.getIdentification();

    /**
     * The meta object literal for the '<em><b>Generation Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IDENTIFICATION__GENERATION_TYPE = eINSTANCE.getIdentification_GenerationType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.ValidationImpl <em>Validation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.ValidationImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getValidation()
     * @generated
     */
    EClass VALIDATION = eINSTANCE.getValidation();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDATION__MIN = eINSTANCE.getValidation_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDATION__MAX = eINSTANCE.getValidation_Max();

    /**
     * The meta object literal for the '<em><b>Regex</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALIDATION__REGEX = eINSTANCE.getValidation_Regex();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.RepositoryImpl <em>Repository</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.RepositoryImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getRepository()
     * @generated
     */
    EClass REPOSITORY = eINSTANCE.getRepository();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPOSITORY__ENTITY = eINSTANCE.getRepository_Entity();

    /**
     * The meta object literal for the '<em><b>Queries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPOSITORY__QUERIES = eINSTANCE.getRepository_Queries();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.QueryImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY__NAME = eINSTANCE.getQuery_Name();

    /**
     * The meta object literal for the '<em><b>Is List</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY__IS_LIST = eINSTANCE.getQuery_IsList();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__PARAMS = eINSTANCE.getQuery_Params();

    /**
     * The meta object literal for the '<em><b>Sql Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__SQL_QUERY = eINSTANCE.getQuery_SqlQuery();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.ParamImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__NAME = eINSTANCE.getParam_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM__TYPE = eINSTANCE.getParam_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.SQLQueryImpl <em>SQL Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.SQLQueryImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getSQLQuery()
     * @generated
     */
    EClass SQL_QUERY = eINSTANCE.getSQLQuery();

    /**
     * The meta object literal for the '<em><b>Select</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SQL_QUERY__SELECT = eINSTANCE.getSQLQuery_Select();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SQL_QUERY__FROM = eINSTANCE.getSQLQuery_From();

    /**
     * The meta object literal for the '<em><b>Joins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SQL_QUERY__JOINS = eINSTANCE.getSQLQuery_Joins();

    /**
     * The meta object literal for the '<em><b>Where</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SQL_QUERY__WHERE = eINSTANCE.getSQLQuery_Where();

    /**
     * The meta object literal for the '<em><b>Order</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SQL_QUERY__ORDER = eINSTANCE.getSQLQuery_Order();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.SelectImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Is Distinct</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__IS_DISTINCT = eINSTANCE.getSelect_IsDistinct();

    /**
     * The meta object literal for the '<em><b>Clause</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__CLAUSE = eINSTANCE.getSelect_Clause();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.FromImpl <em>From</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.FromImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getFrom()
     * @generated
     */
    EClass FROM = eINSTANCE.getFrom();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FROM__ENTITY = eINSTANCE.getFrom_Entity();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FROM__ALIAS = eINSTANCE.getFrom_Alias();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.JoinImpl <em>Join</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.JoinImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getJoin()
     * @generated
     */
    EClass JOIN = eINSTANCE.getJoin();

    /**
     * The meta object literal for the '<em><b>Join Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOIN__JOIN_TYPE = eINSTANCE.getJoin_JoinType();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JOIN__ENTITY = eINSTANCE.getJoin_Entity();

    /**
     * The meta object literal for the '<em><b>Alias</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOIN__ALIAS = eINSTANCE.getJoin_Alias();

    /**
     * The meta object literal for the '<em><b>Join Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute JOIN__JOIN_CONDITION = eINSTANCE.getJoin_JoinCondition();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.WhereImpl <em>Where</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.WhereImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getWhere()
     * @generated
     */
    EClass WHERE = eINSTANCE.getWhere();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE__CONDITION = eINSTANCE.getWhere_Condition();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.socialRequest.impl.OrderImpl <em>Order</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.socialRequest.impl.OrderImpl
     * @see org.xtext.example.mydsl.socialRequest.impl.SocialRequestPackageImpl#getOrder()
     * @generated
     */
    EClass ORDER = eINSTANCE.getOrder();

    /**
     * The meta object literal for the '<em><b>Order</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ORDER__ORDER = eINSTANCE.getOrder_Order();

  }

} //SocialRequestPackage
