image: java:8

stages:
  - test
  - build

before_script:
  - chmod +x mvnw
  - cd SocialRequest

test:
  stage: test
  script: ./mvnw test

build:
  stage: build
  script: ./mvnw package
  artifacts:
    expire_in: 1 day
    paths:
      - target/socialrequest-0.0.1-SNAPSHOT.jar
  only:
    - master
    - develop
