stages:
  - test
  - build
  - docker-build

test:
  image: java:8
  stage: test
  before_script:
    - chmod +x mvnw
  script: ./mvnw test

build:
  image: java:8
  stage: build
  before_script:
    - chmod +x mvnw
  script: ./mvnw package
  artifacts:
    expire_in: 1 day
    paths:
      - target/*.jar
  only:
    - master

# docker-build:
#   image: docker:latest
#   services:
#     - docker:dind
#   stage: docker-build
#   before_script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#     - docker push "$CI_REGISTRY_IMAGE"
#   only:
#     - master

# To set up an automatic push to docker hub, configure the pipeline env settings, the following way:
# CI_REGISTRY_USER=username
# CI_REGISTRY_PASSWORD=********
# CI_REGISTRY=docker.io
# CI_REGISTRY_IMAGE=index.docker.io/<username>/<image_name>
