image: java:8

stages:
  - test
  - build

test:
  stage: test
  before_script:
    - chmod +x mvnw
  script: ./mvnw test

build:
  stage: build
  before_script:
    - chmod +x mvnw
  script: ./mvnw package
  artifacts:
    expire_in: 1 day
    paths:
      - target/*.jar
  only:
    - master
