image: java:8

stages:
  - test
  - build

.test: &test_config
  stage: test
  before_script:
    - cd $FOLDER_NAME
    - chmod +x mvnw
  script: ./mvnw test

.build: &build_config
  stage: build
  before_script:
    - cd $FOLDER_NAME
    - chmod +x mvnw
  script: ./mvnw package
  artifacts:
    expire_in: 1 day
    paths:
      - target/$PROJECT_NAME-*-SNAPSHOT.jar
  only:
    - master

test:SocialRequest:
  extends: .test
  variables:
    FOLDER_NAME: SocialRequest

build:SocialRequest:
  extends: .build
  variables:
    FOLDER_NAME: SocialRequest
    PROJECT_NAME: socialrequest

test:SocialRequest-Maps:
  extends: .test
  variables:
    FOLDER_NAME: SocialRequest-Maps

build:SocialRequest-Maps:
  extends: .build
  variables:
    FOLDER_NAME: SocialRequest-Maps
    PROJECT_NAME: maps

test:SocialRequest-Leaderboard:
  extends: .test
  variables:
    FOLDER_NAME: SocialRequest-Leaderboard

build:SocialRequest:
  extends: .build
  variables:
    FOLDER_NAME: SocialRequest-Leaderboard
    PROJECT_NAME: leaderboard
