version: "3.7"

services:
  activemq:
    image: rmohr/activemq
    ports:
      # JMS
      - "61616:61616"
      # UI
      - "8161:8161"
      # AMQP
      - "5672:5672"
      # STOMP
      - "61613:61613"
      # MQTT
      - "1883:1883"
      # WS
      - "61614:61614"
    volumes: 
      - "activemq-data:/opt/activemq/conf"
      - "activemq-data:/data/activemq"
      - "activemq-data:/var/log/activemq"

volumes:
  activemq-data: