/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.SocialRequest.ui.internal.SocialRequestActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SocialRequestExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SocialRequestActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SocialRequestActivator activator = SocialRequestActivator.getInstance();
		return activator != null ? activator.getInjector(SocialRequestActivator.ORG_XTEXT_EXAMPLE_MYDSL_SOCIALREQUEST) : null;
	}

}
